### PR TITLE
fix(api): resolve relative paths

### LINKED ISSUE #364: npx create-instantsearch-app not working
Hi folks! 👋 

I ran this `npx` command found at https://www.algolia.com/doc/guides/building-search-ui/getting-started/js/?language=js#bootstrap-your-application, but it didn't seem to work. Can't tell if that last message is an error, but I don't see a new directory where I ran the command:

```
$ npx create-instantsearch-app ais-ecommerce-demo-app \
  --template "InstantSearch.js" \
  --app-id B1G2GM9NG0 \
  --api-key aadef574be1f9252bb48d4ea09b5cfe5 \
  --index-name demo_ecommerce \
  --attributes-to-display name

npx: installed 148 in 4.223s

Creating a new InstantSearch app in ais-ecommerce-demo-app.

The template directory must contain a configuration file `.template.js` or must be one of those: Angular InstantSearch, Autocomplete.js, InstantSearch Android, InstantSearch iOS, InstantSearch.js, InstantSearch.js 2, JavaScript Client, JavaScript Helper, React InstantSearch, React InstantSearch Native, Vue InstantSearch
```

### PR DESCRIPTION
**Pull request by francoischalifour**
The template paths are given with relative paths to the API, so adding `path.resolve` makes sure that the path becomes absolute and exists.

I added an end-to-end test with a relative path to make sure it's resolved.

This should close #364.

### CODE REVIEW

File: src/api/check-config.js [hunk 1]
```diff
@@ -17,10 +17,7 @@ function getOptions({ supportedTemplates }) {
     },
     template: {
       validate(input) {
-        return (
-          supportedTemplates.includes(input) ||
```
Comment (francoischalifour) [inline src/api/check-config.js]: This check was unnecessary because the `input` is always a relative path now (not a string like `"InstantSearch.js"`).

File: src/utils/index.js [hunk 2]
```diff
@@ -61,7 +61,7 @@ function checkAppPath(appPath) {
 
 function getAppTemplateConfig(templatePath, { loadFileFn = require } = {}) {
   try {
-    return loadFileFn(`${templatePath}/.template.js`);
+    return loadFileFn(path.resolve(`${templatePath}/.template.js`));
```
Comment (Haroenv) [inline src/utils/index.js]: probably best to use path.join, so it works on Windows?

Comment (Haroenv) [reply src/utils/index.js]: something that should be added everywhere though, not just here. If we decide to properly support windows, we can add CI for that etc.
